In [ ]:
! unzip /content/drive/MyDrive/Colab\ Notebooks/Dataset.zip

Archive:  /content/drive/MyDrive/Colab Notebooks/Dataset.zip
  inflating: olist_customers_dataset.csv
  inflating: olist_geolocation_dataset.csv
  inflating: olist_order_items_dataset.csv
  inflating: olist_order_payments_dataset.csv
  inflating: olist_order_reviews_dataset.csv
  inflating: olist_orders_dataset.csv
  inflating: olist_products_dataset.csv
  inflating: olist_sellers_dataset.csv
  inflating: product_category_name_translation.csv

In [ ]:
# GEO location lat/lng
import pandas as pd
geo_df = pd.read_csv('/content/olist_geolocation_dataset.csv')
geo_df

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [ ]:
# customer unique ID
import pandas as pd


cus_df = pd.read_csv('/content/olist_customers_dataset.csv')
display(cus_df)
# unique ID
len_uniqueid = len(cus_df["customer_unique_id"].unique())
print(len_uniqueid)
#cus_df_noDup = cus_df.drop_duplicates(subset=['customer_id','customer_unique_id'])
pd.DataFrame(cus_df['customer_state']).value_counts().head(10)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

96096

customer_state
SP                41746
RJ                12852
MG                11635
RS                 5466
PR                 5045
SC                 3637
BA                 3380
DF                 2140
ES                 2033
GO                 2020
dtype: int64

# Order_dataset2 is the source of MasterDF later on

In [ ]:
# Order ID dataset
order_dataset = pd.read_csv('/content/olist_orders_dataset.csv')
order_dataset

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [ ]:
order_dataset['order_status'].value_counts()

delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: order_status, dtype: int64

In [ ]:
# Check if order status is negative, there are date/time provided or not. For finding average end-to-end delivery time
# shipped/canceled/unavailable/invoiced/processing/created/approved missing time/date value
order_dataset[order_dataset['order_status'] == "processing"]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaN,NaN,2017-10-03 00:00:00
324,d3c8851a6651eeff2f73b0e011ac45d0,957f8e082185574de25992dc659ebbc0,processing,2016-10-05 22:44:13,2016-10-06 15:51:05,NaN,NaN,2016-12-09 00:00:00
741,6a6c7d523fd59eb5bbefc007331af717,d954782ec6c0e911292c8a80757ef28d,processing,2017-11-24 20:09:33,2017-11-24 23:15:15,NaN,NaN,2017-12-20 00:00:00
1192,745e1d4a7f8c4b548881788d4113bb1d,7198d7088442e4ddfe553353d8ddc957,processing,2017-11-17 06:34:36,2017-11-18 02:15:40,NaN,NaN,2017-12-12 00:00:00
1516,1d52ba7197c7acebbb4f826f6585536f,c9c7fe860d602373a9e93f8bfe9d877a,processing,2017-02-13 18:32:55,2017-02-13 18:43:55,NaN,NaN,2017-04-04 00:00:00
...,...,...,...,...,...,...,...,...
97400,dcdfc540e42725663242bb884c28f0a6,38972104038aa68fcc61277dbf6e7ca9,processing,2017-10-30 10:46:44,2017-10-30 11:09:55,NaN,NaN,2017-11-23 00:00:00
97666,e471815e7114cdb474064f7dbb1a8b67,092c9316ae71b2fe43e526043f351967,processing,2017-12-20 11:00:02,2017-12-20 11:10:43,NaN,NaN,2018-02-02 00:00:00
98089,10951d02d64917a34959abeb8130601e,3e6754e591ff3568ccc5bf69a649918c,processing,2018-02-13 21:02:02,2018-02-15 04:11:21,NaN,NaN,2018-03-13 00:00:00
99140,aea0db338150b526dde24f6fd953a5ed,379a02efdc6a56bd27f99b95fc2f6c06,processing,2017-12-26 21:56:13,2017-12-26 22:05:26,NaN,NaN,2018-01-26 00:00:00
99313,e9e64a17afa9653aacf2616d94c005b8,b4cd0522e632e481f8eaf766a2646e86,processing,2018-01-05 23:07:24,2018-01-09 07:18:05,NaN,NaN,2018-02-06 00:00:00

In [ ]:
order_dataset2 = order_dataset.copy()
# Drop status but delivered (Assume only delivered can get $)
values_to_drop = ["shipped", "canceled", "unavailable", "invoiced", "processing", "created", "approved"]
order_dataset2 = order_dataset2[~order_dataset2["order_status"].isin(values_to_drop)]
order_dataset2

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [ ]:
order_dataset2[order_dataset2['order_purchase_timestamp'].isnull()]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

# clean order_approved_at


> 縮排段落

In [ ]:
# check the order_dataset2 if there is null NaT value
order_dataset2[order_dataset2['order_approved_at'].isnull()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
5323,e04abd8149ef81b95221e88f6ed9ab6a,2127dc6603ac33544953ef05ec155771,delivered,2017-02-18 14:40:00,NaN,2017-02-23 12:04:47,2017-03-01 13:25:33,2017-03-17 00:00:00
16567,8a9adc69528e1001fc68dd0aaebbb54a,4c1ccc74e00993733742a3c786dc3c1f,delivered,2017-02-18 12:45:31,NaN,2017-02-23 09:01:52,2017-03-02 10:05:06,2017-03-21 00:00:00
19031,7013bcfc1c97fe719a7b5e05e61c12db,2941af76d38100e0f8740a374f1a5dc3,delivered,2017-02-18 13:29:47,NaN,2017-02-22 16:25:25,2017-03-01 08:07:38,2017-03-17 00:00:00
22663,5cf925b116421afa85ee25e99b4c34fb,29c35fc91fc13fb5073c8f30505d860d,delivered,2017-02-18 16:48:35,NaN,2017-02-22 11:23:10,2017-03-09 07:28:47,2017-03-31 00:00:00
23156,12a95a3c06dbaec84bcfb0e2da5d228a,1e101e0daffaddce8159d25a8e53f2b2,delivered,2017-02-17 13:05:55,NaN,2017-02-22 11:23:11,2017-03-02 11:09:19,2017-03-20 00:00:00
26800,c1d4211b3dae76144deccd6c74144a88,684cb238dc5b5d6366244e0e0776b450,delivered,2017-01-19 12:48:08,NaN,2017-01-25 14:56:50,2017-01-30 18:16:01,2017-03-01 00:00:00
38290,d69e5d356402adc8cf17e08b5033acfb,68d081753ad4fe22fc4d410a9eb1ca01,delivered,2017-02-19 01:28:47,NaN,2017-02-23 03:11:48,2017-03-02 03:41:58,2017-03-27 00:00:00
39334,d77031d6a3c8a52f019764e68f211c69,0bf35cac6cc7327065da879e2d90fae8,delivered,2017-02-18 11:04:19,NaN,2017-02-23 07:23:36,2017-03-02 16:15:23,2017-03-22 00:00:00
48401,7002a78c79c519ac54022d4f8a65e6e8,d5de688c321096d15508faae67a27051,delivered,2017-01-19 22:26:59,NaN,2017-01-27 11:08:05,2017-02-06 14:22:19,2017-03-16 00:00:00
61743,2eecb0d85f281280f79fa00f9cec1a95,a3d3c38e58b9d2dfb9207cab690b6310,delivered,2017-02-17 17:21:55,NaN,2017-02-22 11:42:51,2017-03-03 12:16:03,2017-03-20 00:00:00
63052,51eb2eebd5d76a24625b31c33dd41449,07a2a7e0f63fd8cb757ed77d4245623c,delivered,2017-02-18 15:52:27,NaN,2017-02-23 03:09:14,2017-03-07 13:57:47,2017-03-29 00:00:00
67697,88083e8f64d95b932164187484d90212,f67cd1a215aae2a1074638bbd35a223a,delivered,2017-02-18 22:49:19,NaN,2017-02-22 11:31:06,2017-03-02 12:06:06,2017-03-21 00:00:00
72407,3c0b8706b065f9919d0505d3b3343881,d85919cb3c0529589c6fa617f5f43281,delivered,2017-02-17 15:53:27,NaN,2017-02-22 11:31:30,2017-03-03 11:47:47,2017-03-23 00:00:00
84999,2babbb4b15e6d2dfe95e2de765c97bce,74bebaf46603f9340e3b50c6b086f992,delivered,2017-02-18 17:15:03,NaN,2017-02-22 11:23:11,2017-03-03 18:43:43,2017-03-31 00:00:00

In [ ]:
# Use fillna to assume order_purchase_timestamp = order_approved_at
order_dataset2['order_approved_at'].fillna(order_dataset2['order_purchase_timestamp'], inplace=True)
#order_dataset2[order_dataset2['order_approved_at'].isnull()]

#Check the NaN value order_id to find if it is corrected
order_dataset2[order_dataset2['order_id']=='8a9adc69528e1001fc68dd0aaebbb54a']['order_approved_at']

16567    2017-02-18 12:45:31
Name: order_approved_at, dtype: object

# clean order_delivered_carrier_date

In [ ]:
order_dataset2[order_dataset2['order_delivered_carrier_date'].isnull()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
73222,2aa91108853cecb43c84a5dc5b277475,afeb16c7f46396c0ed54acb45ccaaa40,delivered,2017-09-29 08:52:58,2017-09-29 09:07:16,NaN,2017-11-20 19:44:47,2017-11-14 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaN,NaN,2017-06-23 00:00:00

In [ ]:
# Use fillna to assume order_approved_at = order_delivered_carrier_date
order_dataset2['order_delivered_carrier_date'].fillna(order_dataset2['order_approved_at'], inplace=True)

#Check the NaN value order_id to find if it is corrected
order_dataset2[order_dataset2['order_id']=='2aa91108853cecb43c84a5dc5b277475']['order_delivered_carrier_date']

73222    2017-09-29 09:07:16
Name: order_delivered_carrier_date, dtype: object

# clean order_delivered_customer_date

In [ ]:
order_dataset2[order_dataset2['order_delivered_customer_date'].isnull()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaN,2017-12-18 00:00:00
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaN,2018-07-16 00:00:00
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaN,2018-07-24 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,2017-05-25 23:30:16,NaN,2017-06-23 00:00:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaN,2018-06-26 00:00:00
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaN,2018-07-19 00:00:00

In [ ]:
# Use fillna to assume order_delivered_customer_date = order_estimated_delivery_date
order_dataset2['order_delivered_customer_date'].fillna(order_dataset2['order_estimated_delivery_date'], inplace=True)

#Check the NaN value order_id to find if it is corrected
order_dataset2[order_dataset2['order_id']=='2d1e2d5bf4dc7227b3bfebb81328c15f']['order_delivered_customer_date']

3002    2017-12-18 00:00:00
Name: order_delivered_customer_date, dtype: object

In [ ]:
order_dataset2[order_dataset2['order_estimated_delivery_date'].isnull()]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [ ]:
# Check if there is all cleaned

order_dataset2[order_dataset2['order_delivered_customer_date'].isna()]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [ ]:
order_dataset2[order_dataset2['order_delivered_customer_date'] == 'NaT']

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

# Get the total delivery days

In [ ]:
#Average days and time for delivery
import pandas as pd
from datetime import datetime

order_dataset2['order_purchase_timestamp'] = pd.to_datetime(order_dataset2['order_purchase_timestamp'])
order_dataset2['order_delivered_customer_date'] = pd.to_datetime(order_dataset2['order_delivered_customer_date'])

order_dataset2["order_purchase_date"] = pd.to_datetime(order_dataset2['order_purchase_timestamp'].dt.strftime('%Y-%m-%d'))
order_dataset2['order_delivered_date'] = pd.to_datetime(order_dataset2["order_delivered_customer_date"].dt.strftime('%Y-%m-%d'))
order_dataset2["order_purchase_time"] = pd.to_datetime(order_dataset2['order_purchase_timestamp'].dt.strftime('%Y-%m-%d %H:%M:%S'))
order_dataset2['order_delivered_time'] = pd.to_datetime(order_dataset2["order_delivered_customer_date"].dt.strftime('%Y-%m-%d %H:%M:%S'))

order_dataset2['total_date_of_delivery'] = order_dataset2['order_delivered_date'].dt.date - order_dataset2["order_purchase_date"].dt.date #count days

#Filter the value to show sentence
mean_days = str(order_dataset2['total_date_of_delivery'].mean()).split('days')[0]
get_plus_time = str(order_dataset2['total_date_of_delivery'].mean()).split('days')[1]
adjust_time = get_plus_time.split('.')[0]
adjust_time
print(f'The average days that complete the order: {mean_days} days + time: {adjust_time}')
order_dataset2

The average days that complete the order: 12  days + time:  11:56:53

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_date,order_delivered_date,order_purchase_time,order_delivered_time,total_date_of_delivery
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2017-10-02,2017-10-10,2017-10-02 10:56:33,2017-10-10 21:25:13,8 days
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,2018-07-24,2018-08-07,2018-07-24 20:41:37,2018-08-07 15:27:45,14 days
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,2018-08-08,2018-08-17,2018-08-08 08:38:49,2018-08-17 18:06:29,9 days
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,2017-11-18,2017-12-02,2017-11-18 19:28:06,2017-12-02 00:28:42,14 days
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,2018-02-13,2018-02-16,2018-02-13 21:18:39,2018-02-16 18:17:02,3 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,2017-03-09,2017-03-17,2017-03-09 09:54:05,2017-03-17 15:08:01,8 days
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,2018-02-06,2018-02-28,2018-02-06 12:58:58,2018-02-28 17:37:56,22 days
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,2017-08-27,2017-09-21,2017-08-27 14:46:43,2017-09-21 11:24:17,25 days
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2018-01-08,2018-01-25,2018-01-08 21:28:27,2018-01-25 23:32:54,17 days
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,2018-03-08,2018-03-16,2018-03-08 20:57:30,2018-03-16 13:08:30,8 days

In [ ]:
order_dataset2[order_dataset2['customer_id'].isna()]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, order_purchase_date, order_delivered_date, order_purchase_time, order_delivered_time, total_date_of_delivery]
Index: []

In [ ]:
#Check null value
order_dataset2[order_dataset2['order_delivered_customer_date'] == 'NaT']

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, order_purchase_date, order_delivered_date, order_purchase_time, order_delivered_time, total_date_of_delivery]
Index: []

In [ ]:
mapping_dict = order_dataset2['total_date_of_delivery'].astype(str).str.replace(' days','').to_dict()
order_dataset2['total_date_of_delivery'] = order_dataset2.index.map(mapping_dict)
order_dataset2

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_date,order_delivered_date,order_purchase_time,order_delivered_time,total_date_of_delivery
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2017-10-02,2017-10-10,2017-10-02 10:56:33,2017-10-10 21:25:13,8
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,2018-07-24,2018-08-07,2018-07-24 20:41:37,2018-08-07 15:27:45,14
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,2018-08-08,2018-08-17,2018-08-08 08:38:49,2018-08-17 18:06:29,9
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,2017-11-18,2017-12-02,2017-11-18 19:28:06,2017-12-02 00:28:42,14
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,2018-02-13,2018-02-16,2018-02-13 21:18:39,2018-02-16 18:17:02,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,2017-03-09,2017-03-17,2017-03-09 09:54:05,2017-03-17 15:08:01,8
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,2018-02-06,2018-02-28,2018-02-06 12:58:58,2018-02-28 17:37:56,22
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,2017-08-27,2017-09-21,2017-08-27 14:46:43,2017-09-21 11:24:17,25
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2018-01-08,2018-01-25,2018-01-08 21:28:27,2018-01-25 23:32:54,17
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,2018-03-08,2018-03-16,2018-03-08 20:57:30,2018-03-16 13:08:30,8

In [ ]:
order_dataset2['total_date_of_delivery'] = order_dataset2['total_date_of_delivery'].astype(int)

In [ ]:
order_dataset2['total_date_of_delivery'].describe()

count    96478.000000
mean        12.497844
std          9.555373
min          0.000000
25%          7.000000
50%         10.000000
75%         16.000000
max        210.000000
Name: total_date_of_delivery, dtype: float64

In [ ]:
#Check if there is null value
order_dataset2[order_dataset2['total_date_of_delivery'].isnull()]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, order_purchase_date, order_delivered_date, order_purchase_time, order_delivered_time, total_date_of_delivery]
Index: []

[0 rows x 13 columns]

# Try to find out unique customer will buy how many items in a order

In [ ]:
#state_fullname / average hosehold income by state (creatw a new csv into powerbi)
import pandas as pd
mapping = {"AC":'Acre',"AL":'Alagoas',"AM":'Amazonas',
'AP':'Amapá','BA':'Bahia','CE':'Ceará',
'DF':'Distrito Federal','ES':'Espírito Santo','GO':'Goiás',
'MA':'Maranhão',
'MG':'Minas Gerais',
'MS':'Mato Grosso do Sul',
'MT':'Mato Grosso',
'PA':'Pará',
'PB':'Paraíba',
'PE':'Pernambuco',
'PI':'Piauí',
'PR':'Paraná',
'RJ':'Rio de Janeiro',
'RN':'Rio Grande do Norte',
'RO':'Rondônia',
'RR':'Roraima',
'RS':'Rio Grande do Sul',
'SC':'Santa Catarina',
'SE':'Sergipe',
'SP':'São Paulo',
'TO':'Tocantins'}

cust_data = pd.read_csv('/content/olist_customers_dataset.csv')
cust_order_df = pd.merge(order_dataset,cust_data,on="customer_id")
#Relocate the columns
cust_order_df = cust_order_df[["order_id","customer_id","customer_unique_id","customer_city","customer_state"]]
cust_order_df['state_fullname'] = cust_order_df["customer_state"].map(mapping)
cust_order_df

,order_id,customer_id,customer_unique_id,customer_city,customer_state,state_fullname
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,São Paulo
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,af07308b275d755c9edb36a90c618231,barreiras,BA,Bahia
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO,Goiás
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN,Rio Grande do Norte
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP,São Paulo
...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,6359f309b166b0196dbf7ad2ac62bb5a,sao jose dos campos,SP,São Paulo
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,da62f9e57a76d978d02ab5362c509660,praia grande,SP,São Paulo
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,737520a9aad80b3fbbdad19b66b37b30,nova vicosa,BA,Bahia
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ,Rio de Janeiro
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,60350aa974b26ff12caad89e55993bd6,lapa,PR,Paraná

In [ ]:
cust_order_df.to_csv(r"/content/drive/MyDrive/Colab Notebooks/customerID_state.csv")

In [ ]:
#test
cust_order_df[cust_order_df["customer_unique_id"] == '0246128cbe42bad650aca67dea148ecb']

,order_id,customer_id,customer_unique_id,customer_city,customer_state,state_fullname
23220,eebb8622e78c78a62c7a2b941d76680f,2e5e192daace5791ff9fdb7cc0cc6d1c,0246128cbe42bad650aca67dea148ecb,recife,PE,Pernambuco

In [ ]:
order_dict = cust_order_df.groupby("customer_unique_id")["order_id"].count().to_dict()
cust_order_df["order_freq_from_customer"] = cust_order_df["customer_unique_id"].map(order_dict)
order_freq_desc = cust_order_df['order_freq_from_customer'].describe()
print(order_freq_desc)
average_oder = order_freq_desc.iloc[1]
max_order_customer = order_freq_desc.iloc[7]
print(f'Average order frequency from a customer: {average_oder.round(3)} orders, Max order from a customer: {int(max_order_customer)} orders')

count    99441.000000
mean         1.079223
std          0.396154
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         17.000000
Name: order_freq_from_customer, dtype: float64
Average order frequency from a customer: 1.079 orders, Max order from a customer: 17 orders

In [ ]:
#Check the order frequency from a customer
cust_order_df["order_freq_from_customer"].value_counts()

1     93099
2      5490
3       609
4       120
5        40
6        36
7        21
17       17
9         9
Name: order_freq_from_customer, dtype: int64

In [ ]:
#
#DF the customers with order frequency
cust_order_df["order_freq_from_customer"].value_counts()
top11_order_cust = cust_order_df[cust_order_df["order_freq_from_customer"]>=6]["customer_unique_id"].unique()
top11_order_cust_list = list(top11_order_cust)
top11_order_cust_list

['12f5d6e1cbf93dafd9dcc19095df0b3d',
 '8d50f5eadf50201ccdcedfb9e2ac8455',
 '3e43e6105506432c953e165fb2acf44c',
 'ca77025e7201e3b30c44b472ff346268',
 '1b6c7548a2a1f9037c1fd3ddfed95f33',
 'de34b16117594161a6a89c50b289d35a',
 '6469f99c1f9dfae7733b25662e7f1782',
 '47c1a3033b8b77b3ab6e109eb4d5fdf3',
 'f0e310a6839dce9de1638e0fe5ab282a',
 'dc813062e0fc23409cd255f7f53c7074',
 '63cfc61cee11cbe306bff5857d00bfe4']

In [ ]:
cust_order_df[cust_order_df['customer_unique_id'] == '8d50f5eadf50201ccdcedfb9e2ac8455']

In [ ]:
order_dataset['order_id']

In [ ]:
order_dataset['order_status'].value_counts()

# order item dataset (find customer buy how many items in a order)

In [ ]:
#Order item dataset
order_item = pd.read_csv('/content/olist_order_items_dataset.csv')
order_item

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [ ]:
len(order_item['order_id'].unique()) #有order_id重覆

98666

In [ ]:
#找order中產品數量平均數 correct
group_dict = order_item.groupby('order_id')['product_id'].count().to_dict()
order_item['num_of_product'] = order_item['order_id'].map(group_dict)
product_desc = order_item['num_of_product'].describe()
print(product_desc)
average_itemOrder = order_item['num_of_product'].mean()
max_unit = product_desc.iloc[7]
print(f'Average number of product will buy in a order: {average_itemOrder.round(2)} items, Max unit in a order: {int(max_unit)} items')

count    112650.000000
mean          1.395668
std           1.120101
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max          21.000000
Name: num_of_product, dtype: float64
Average number of product will buy in a order: 1.4 items, Max unit in a order: 21 items

# Merge 2 df for info

In [ ]:
#merge 2 df for info
df_item = pd.read_csv('/content/olist_order_items_dataset.csv') # item
order_dataset2 # order info

new_dff = pd.merge(df_item,order_dataset2,on='order_id')
new_dff
#len(new_dff['seller_id'].unique()) #seller有重覆
#cusgroup_dict = new_dff.groupby('customer')

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_date,order_delivered_date,order_purchase_time,order_delivered_time,total_date_of_delivery
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29 00:00:00,2017-09-13,2017-09-20,2017-09-13 08:59:02,2017-09-20 23:43:48,7
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15 00:00:00,2017-04-26,2017-05-12,2017-04-26 10:53:06,2017-05-12 16:04:24,16
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05 00:00:00,2018-01-14,2018-01-22,2018-01-14 14:33:31,2018-01-22 13:19:16,8
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20 00:00:00,2018-08-08,2018-08-14,2018-08-08 10:00:35,2018-08-14 13:32:39,6
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17 00:00:00,2017-02-04,2017-03-01,2017-02-04 13:57:51,2017-03-01 16:42:31,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110192,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,b51593916b4b8e0d6f66f2ae24f2673d,delivered,2018-04-23 13:57:06,2018-04-25 04:11:01,2018-04-25 12:09:00,2018-05-10 22:56:40,2018-05-18 00:00:00,2018-04-23,2018-05-10,2018-04-23 13:57:06,2018-05-10 22:56:40,17
110193,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,84c5d4fbaf120aae381fad077416eaa0,delivered,2018-07-14 10:26:46,2018-07-17 04:31:48,2018-07-17 08:05:00,2018-07-23 20:31:55,2018-08-01 00:00:00,2018-07-14,2018-07-23,2018-07-14 10:26:46,2018-07-23 20:31:55,9
110194,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,29309aa813182aaddc9b259e31b870e6,delivered,2017-10-23 17:07:56,2017-10-24 17:14:25,2017-10-26 15:13:14,2017-10-28 12:22:22,2017-11-10 00:00:00,2017-10-23,2017-10-28,2017-10-23 17:07:56,2017-10-28 12:22:22,5
110195,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,b5e6afd5a41800fdf401e0272ca74655,delivered,2017-08-14 23:02:59,2017-08-15 00:04:32,2017-08-15 19:02:53,2017-08-16 21:59:40,2017-08-25 00:00:00,2017-08-14,2017-08-16,2017-08-14 23:02:59,2017-08-16 21:59:40,2
110196,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,2018-06-09 17:10:13,2018-06-11 14:11:00,2018-06-14 17:56:26,2018-06-28 00:00:00,2018-06-09,2018-06-14,2018-06-09 17:00:18,2018-06-14 17:56:26,5

In [ ]:
# Check if order_dataset2 is valid after merge (No null)
new_dff[new_dff['order_delivered_date'].isnull()]

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, order_purchase_date, order_delivered_date, order_purchase_time, order_delivered_time, total_date_of_delivery]
Index: []

In [ ]:
#customer who spend the most money
group_to_dict = new_dff.groupby('order_id')['price'].sum().to_dict()
new_dff['accumulate_price'] = new_dff['order_id'].map(group_to_dict)
price_desc = new_dff['accumulate_price'].describe()
#price_desc
new_dff['accumulate_price'].sort_values(ascending=False).head(50) #購買price總數
new_dff[new_dff['accumulate_price'] >=4590]['customer_id'].unique()

array(['1617b1357756262bfa56ab541c47bc16',
       'c6e2731c5b391845f6800c97401a43a9',
       '24bbf5fd2f2e1b359ee7de94defc4a15',
       '05455dfa7cd02f13d132aa7a6a9729c6',
       'ec5b2ba62e574342386871631fafd3fc',
       '3d979689f636322c62418b6346b1c6d2',
       'df55c14d1476a9a3467f131269c2477f',
       '3fd6777bbce08a352fddd04e4a7cc8f6',
       'f48d464a0baaea338cb25f816991ab1f'], dtype=object)

In [ ]:
#Check customer buy items
new_dff[new_dff['customer_id']=='1617b1357756262bfa56ab541c47bc16']

# Add category to df

In [ ]:
prod_df = pd.read_csv('/content/olist_products_dataset.csv')
category_name = prod_df['product_category_name']
prod_df

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [ ]:
#drop unwanted columns
prod_data = pd.read_csv('/content/olist_products_dataset.csv')
prod_translate = pd.read_csv('/content/product_category_name_translation.csv')

df_newProdData = pd.merge(prod_data,prod_translate,on='product_category_name')
df_category = df_newProdData.drop(columns=['product_name_lenght',
                             'product_description_lenght',
                             'product_photos_qty',
                             'product_weight_g',
                             'product_length_cm',
                             'product_height_cm',
                             'product_width_cm'
                             ])
df_category

,product_id,product_category_name,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,perfumery
1,6a2fb4dd53d2cdb88e0432f1284a004c,perfumaria,perfumery
2,0d009643171aee696f4733340bc2fdd0,perfumaria,perfumery
3,b1eae565a61935e0011ee7682fef9dc9,perfumaria,perfumery
4,8da90b37f0fb171b4877c124f965b1f6,perfumaria,perfumery
...,...,...,...
32323,13b25797ad1e6d6c7cd3cbeb35f8ee7a,moveis_colchao_e_estofado,furniture_mattress_and_upholstery
32324,dc36a7859b743d8610a2bbbaea26ece9,moveis_colchao_e_estofado,furniture_mattress_and_upholstery
32325,107fde0930956120d1e13dd1062fbb46,moveis_colchao_e_estofado,furniture_mattress_and_upholstery
32326,726b4e18f00255e2e63491bcba3f60b8,moveis_colchao_e_estofado,furniture_mattress_and_upholstery
32327,1dceebcc5f23c02ea23e16d5bedca000,cds_dvds_musicais,cds_dvds_musicals

In [ ]:
#Add category in new_dff
df_withCategory = pd.merge(new_dff,df_category,on='product_id')
df_withCategory.drop(columns=['product_category_name'],inplace=True)
df_withCategory
#df_withCategory = df_withCategory[['order_id','order_item_id','product_id','product_category_name_english',
#                                   'seller_id','price','freight_value','customer_id','num_of_product_brought','accumulate_price']]
#top10_spend = df_withCategory[df_withCategory['accumulate_price'] >=4590]['customer_id'].unique()
#top10_spend_list = list(top10_spend)
#top10_spend_list

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,...,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_date,order_delivered_date,order_purchase_time,order_delivered_time,total_date_of_delivery,accumulate_price,product_category_name_english
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,...,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29 00:00:00,2017-09-13,2017-09-20,2017-09-13 08:59:02,2017-09-20 23:43:48,7,58.9,cool_stuff
1,130898c0987d1801452a8ed92a670612,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-07-05 02:44:11,55.9,17.96,e6eecc5a77de221464d1c4eaff0a9b64,delivered,2017-06-28 11:52:20,...,2017-07-05 12:00:33,2017-07-13 20:39:29,2017-07-26 00:00:00,2017-06-28,2017-07-13,2017-06-28 11:52:20,2017-07-13 20:39:29,15,55.9,cool_stuff
2,532ed5e14e24ae1f0d735b91524b98b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2018-05-23 10:56:25,64.9,18.33,4ef55bf80f711b372afebcb7c715344a,delivered,2018-05-18 10:25:53,...,2018-05-23 14:05:00,2018-06-04 18:34:26,2018-06-07 00:00:00,2018-05-18,2018-06-04,2018-05-18 10:25:53,2018-06-04 18:34:26,17,64.9,cool_stuff
3,6f8c31653edb8c83e1a739408b5ff750,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-07 18:55:08,58.9,16.17,30407a72ad8b3f4df4d15369126b20c9,delivered,2017-08-01 18:38:42,...,2017-08-02 19:07:36,2017-08-09 21:26:33,2017-08-25 00:00:00,2017-08-01,2017-08-09,2017-08-01 18:38:42,2017-08-09 21:26:33,8,58.9,cool_stuff
4,7d19f4ef4d04461989632411b7e588b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-16 22:05:11,58.9,13.29,91a792fef70ecd8cc69d3c7feb3d12da,delivered,2017-08-10 21:48:40,...,2017-08-11 19:43:07,2017-08-24 20:04:21,2017-09-01 00:00:00,2017-08-10,2017-08-24,2017-08-10 21:48:40,2017-08-24 20:04:21,14,58.9,cool_stuff
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108633,ffebd80e3291e811c308365936897efd,1,4cc4d02efc8f249c13355147fb44e34d,d1c7fa84e48cfa21a0e595167c1c500e,2018-07-18 20:23:55,129.9,51.20,050309b91cc5e04e68841938e7984aaf,delivered,2018-07-13 20:04:05,...,2018-07-17 10:03:00,2018-07-23 19:44:45,2018-08-07 00:00:00,2018-07-13,2018-07-23,2018-07-13 20:04:05,2018-07-23 19:44:45,10,129.9,garden_tools
108634,ffee31fb4b5e35c9123608015637c495,1,b10ecf8e33aaaea419a9fa860ea80fb5,0241d4d5d36f10f80c644447315af0bd,2018-08-21 10:10:11,99.0,13.52,11e0f43ab4e2d2c48348dd9332c0ef80,delivered,2018-08-18 10:00:59,...,2018-08-20 10:01:00,2018-08-21 12:18:57,2018-08-23 00:00:00,2018-08-18,2018-08-21,2018-08-18 10:00:59,2018-08-21 12:18:57,3,99.0,furniture_decor
108635,fff7c4452f050315db1b3f24d9df5fcd,1,dd469c03ad67e201bc2179ef077dcd48,7e93a43ef30c4f03f38b393420bc753a,2017-06-07 17:05:23,736.0,20.91,dec8952e97ef6124259c56914fb3569c,delivered,2017-06-01 16:53:03,...,2017-06-02 11:49:53,2017-06-08 13:04:40,2017-06-26 00:00:00,2017-06-01,2017-06-08,2017-06-01 16:53:03,2017-06-08 13:04:40,7,736.0,watches_gifts
108636,fffa82886406ccf10c7b4e35c4ff2788,1,bbe7651fef80287a816ead73f065fc4b,8f2ce03f928b567e3d56181ae20ae952,2017-12-22 17:31:42,229.9,44.02,a5201e1a6d71a8d21e869151bd5b4085,delivered,2017-12-18 16:33:07,...,2017-12-20 18:55:00,2018-01-08 18:23:10,2018-01-24 00:00:00,2017-12-18,2018-01-08,2017-12-18 16:33:07,2018-01-08 18:23:10,21,229.9,sports_leisure
108637,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.0,12.79,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-06-09 17:00:18,...,2018-06-11 14:11:00,2018-06-14 17:56:26,2018-06-28 00:00:00,2018-06-09,2018-06-14,2018-06-09 17:00:18,2018-06-14 17:56:26,5,43.0,bed_bath_table

In [ ]:
df_withCategory[df_withCategory['product_category_name_english'].isnull()]

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, order_purchase_date, order_delivered_date, order_purchase_time, order_delivered_time, total_date_of_delivery, accumulate_price, product_category_name_english]
Index: []

[0 rows x 21 columns]

# Way to Master Dataframe

In [ ]:
# drop unneeded columns and join into time dataset #drop customer_id order_status order_purchase_timestamp order_approved_at order_delivered_carrier_date order_delivered_customer_date
# drop order_estimated_delivery_date
df_withCategory_new = df_withCategory.copy()
df_withCategory_clean = df_withCategory_new.drop(columns=['customer_id','order_status','order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date',
                              'order_purchase_date','order_delivered_date','order_purchase_time','order_delivered_time','total_date_of_delivery'])
df_withCategory_clean

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,accumulate_price,product_category_name_english
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,58.9,cool_stuff
1,130898c0987d1801452a8ed92a670612,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-07-05 02:44:11,55.9,17.96,55.9,cool_stuff
2,532ed5e14e24ae1f0d735b91524b98b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2018-05-23 10:56:25,64.9,18.33,64.9,cool_stuff
3,6f8c31653edb8c83e1a739408b5ff750,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-07 18:55:08,58.9,16.17,58.9,cool_stuff
4,7d19f4ef4d04461989632411b7e588b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-16 22:05:11,58.9,13.29,58.9,cool_stuff
...,...,...,...,...,...,...,...,...,...
108633,ffebd80e3291e811c308365936897efd,1,4cc4d02efc8f249c13355147fb44e34d,d1c7fa84e48cfa21a0e595167c1c500e,2018-07-18 20:23:55,129.9,51.20,129.9,garden_tools
108634,ffee31fb4b5e35c9123608015637c495,1,b10ecf8e33aaaea419a9fa860ea80fb5,0241d4d5d36f10f80c644447315af0bd,2018-08-21 10:10:11,99.0,13.52,99.0,furniture_decor
108635,fff7c4452f050315db1b3f24d9df5fcd,1,dd469c03ad67e201bc2179ef077dcd48,7e93a43ef30c4f03f38b393420bc753a,2017-06-07 17:05:23,736.0,20.91,736.0,watches_gifts
108636,fffa82886406ccf10c7b4e35c4ff2788,1,bbe7651fef80287a816ead73f065fc4b,8f2ce03f928b567e3d56181ae20ae952,2017-12-22 17:31:42,229.9,44.02,229.9,sports_leisure
108637,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.0,12.79,43.0,bed_bath_table

In [ ]:
#reference
order_dataset2

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_date,order_delivered_date,order_purchase_time,order_delivered_time,total_date_of_delivery
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2017-10-02,2017-10-10,2017-10-02 10:56:33,2017-10-10 21:25:13,8
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,2018-07-24,2018-08-07,2018-07-24 20:41:37,2018-08-07 15:27:45,14
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,2018-08-08,2018-08-17,2018-08-08 08:38:49,2018-08-17 18:06:29,9
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,2017-11-18,2017-12-02,2017-11-18 19:28:06,2017-12-02 00:28:42,14
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,2018-02-13,2018-02-16,2018-02-13 21:18:39,2018-02-16 18:17:02,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,2017-03-09,2017-03-17,2017-03-09 09:54:05,2017-03-17 15:08:01,8
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,2018-02-06,2018-02-28,2018-02-06 12:58:58,2018-02-28 17:37:56,22
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,2017-08-27,2017-09-21,2017-08-27 14:46:43,2017-09-21 11:24:17,25
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2018-01-08,2018-01-25,2018-01-08 21:28:27,2018-01-25 23:32:54,17
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,2018-03-08,2018-03-16,2018-03-08 20:57:30,2018-03-16 13:08:30,8

In [ ]:
#Add category , merge
merge_order_category = pd.merge(df_withCategory_clean,order_dataset2,on='order_id')
merge_order_category

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,accumulate_price,product_category_name_english,customer_id,...,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_date,order_delivered_date,order_purchase_time,order_delivered_time,total_date_of_delivery
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,58.9,cool_stuff,3ce436f183e68e07877b285a838db11a,...,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29 00:00:00,2017-09-13,2017-09-20,2017-09-13 08:59:02,2017-09-20 23:43:48,7
1,130898c0987d1801452a8ed92a670612,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-07-05 02:44:11,55.9,17.96,55.9,cool_stuff,e6eecc5a77de221464d1c4eaff0a9b64,...,2017-06-28 11:52:20,2017-06-29 02:44:11,2017-07-05 12:00:33,2017-07-13 20:39:29,2017-07-26 00:00:00,2017-06-28,2017-07-13,2017-06-28 11:52:20,2017-07-13 20:39:29,15
2,532ed5e14e24ae1f0d735b91524b98b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2018-05-23 10:56:25,64.9,18.33,64.9,cool_stuff,4ef55bf80f711b372afebcb7c715344a,...,2018-05-18 10:25:53,2018-05-18 12:31:43,2018-05-23 14:05:00,2018-06-04 18:34:26,2018-06-07 00:00:00,2018-05-18,2018-06-04,2018-05-18 10:25:53,2018-06-04 18:34:26,17
3,6f8c31653edb8c83e1a739408b5ff750,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-07 18:55:08,58.9,16.17,58.9,cool_stuff,30407a72ad8b3f4df4d15369126b20c9,...,2017-08-01 18:38:42,2017-08-01 18:55:08,2017-08-02 19:07:36,2017-08-09 21:26:33,2017-08-25 00:00:00,2017-08-01,2017-08-09,2017-08-01 18:38:42,2017-08-09 21:26:33,8
4,7d19f4ef4d04461989632411b7e588b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-16 22:05:11,58.9,13.29,58.9,cool_stuff,91a792fef70ecd8cc69d3c7feb3d12da,...,2017-08-10 21:48:40,2017-08-10 22:05:11,2017-08-11 19:43:07,2017-08-24 20:04:21,2017-09-01 00:00:00,2017-08-10,2017-08-24,2017-08-10 21:48:40,2017-08-24 20:04:21,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108633,ffebd80e3291e811c308365936897efd,1,4cc4d02efc8f249c13355147fb44e34d,d1c7fa84e48cfa21a0e595167c1c500e,2018-07-18 20:23:55,129.9,51.20,129.9,garden_tools,050309b91cc5e04e68841938e7984aaf,...,2018-07-13 20:04:05,2018-07-13 20:23:55,2018-07-17 10:03:00,2018-07-23 19:44:45,2018-08-07 00:00:00,2018-07-13,2018-07-23,2018-07-13 20:04:05,2018-07-23 19:44:45,10
108634,ffee31fb4b5e35c9123608015637c495,1,b10ecf8e33aaaea419a9fa860ea80fb5,0241d4d5d36f10f80c644447315af0bd,2018-08-21 10:10:11,99.0,13.52,99.0,furniture_decor,11e0f43ab4e2d2c48348dd9332c0ef80,...,2018-08-18 10:00:59,2018-08-18 10:10:11,2018-08-20 10:01:00,2018-08-21 12:18:57,2018-08-23 00:00:00,2018-08-18,2018-08-21,2018-08-18 10:00:59,2018-08-21 12:18:57,3
108635,fff7c4452f050315db1b3f24d9df5fcd,1,dd469c03ad67e201bc2179ef077dcd48,7e93a43ef30c4f03f38b393420bc753a,2017-06-07 17:05:23,736.0,20.91,736.0,watches_gifts,dec8952e97ef6124259c56914fb3569c,...,2017-06-01 16:53:03,2017-06-01 17:05:23,2017-06-02 11:49:53,2017-06-08 13:04:40,2017-06-26 00:00:00,2017-06-01,2017-06-08,2017-06-01 16:53:03,2017-06-08 13:04:40,7
108636,fffa82886406ccf10c7b4e35c4ff2788,1,bbe7651fef80287a816ead73f065fc4b,8f2ce03f928b567e3d56181ae20ae952,2017-12-22 17:31:42,229.9,44.02,229.9,sports_leisure,a5201e1a6d71a8d21e869151bd5b4085,...,2017-12-18 16:33:07,2017-12-18 17:33:04,2017-12-20 18:55:00,2018-01-08 18:23:10,2018-01-24 00:00:00,2017-12-18,2018-01-08,2017-12-18 16:33:07,2018-01-08 18:23:10,21
108637,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.0,12.79,43.0,bed_bath_table,96d649da0cc4ff33bb408b199d4c7dcf,...,2018-06-09 17:00:18,2018-06-09 17:10:13,2018-06-11 14:11:00,2018-06-14 17:56:26,2018-06-28 00:00:00,2018-06-09,2018-06-14,2018-06-09 17:00:18,2018-06-14 17:56:26,5

In [ ]:
merge_order_category[merge_order_category['total_date_of_delivery'].isnull()]

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value, accumulate_price, product_category_name_english, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, order_purchase_date, order_delivered_date, order_purchase_time, order_delivered_time, total_date_of_delivery]
Index: []

[0 rows x 21 columns]

#Add product size into dataframe

In [ ]:
prod_data_new = prod_data.copy()
prod_data_drop = prod_data_new.drop(columns=['product_category_name'])
prod_data_drop

,product_id,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [ ]:
merge_order_category_size = pd.merge(merge_order_category,prod_data_drop,on='product_id')
merge_order_category_size

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,accumulate_price,product_category_name_english,customer_id,...,order_purchase_time,order_delivered_time,total_date_of_delivery,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,58.9,cool_stuff,3ce436f183e68e07877b285a838db11a,...,2017-09-13 08:59:02,2017-09-20 23:43:48,7,58.0,598.0,4.0,650.0,28.0,9.0,14.0
1,130898c0987d1801452a8ed92a670612,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-07-05 02:44:11,55.9,17.96,55.9,cool_stuff,e6eecc5a77de221464d1c4eaff0a9b64,...,2017-06-28 11:52:20,2017-07-13 20:39:29,15,58.0,598.0,4.0,650.0,28.0,9.0,14.0
2,532ed5e14e24ae1f0d735b91524b98b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2018-05-23 10:56:25,64.9,18.33,64.9,cool_stuff,4ef55bf80f711b372afebcb7c715344a,...,2018-05-18 10:25:53,2018-06-04 18:34:26,17,58.0,598.0,4.0,650.0,28.0,9.0,14.0
3,6f8c31653edb8c83e1a739408b5ff750,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-07 18:55:08,58.9,16.17,58.9,cool_stuff,30407a72ad8b3f4df4d15369126b20c9,...,2017-08-01 18:38:42,2017-08-09 21:26:33,8,58.0,598.0,4.0,650.0,28.0,9.0,14.0
4,7d19f4ef4d04461989632411b7e588b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-16 22:05:11,58.9,13.29,58.9,cool_stuff,91a792fef70ecd8cc69d3c7feb3d12da,...,2017-08-10 21:48:40,2017-08-24 20:04:21,14,58.0,598.0,4.0,650.0,28.0,9.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108633,ffebd80e3291e811c308365936897efd,1,4cc4d02efc8f249c13355147fb44e34d,d1c7fa84e48cfa21a0e595167c1c500e,2018-07-18 20:23:55,129.9,51.20,129.9,garden_tools,050309b91cc5e04e68841938e7984aaf,...,2018-07-13 20:04:05,2018-07-23 19:44:45,10,37.0,653.0,1.0,6700.0,35.0,12.0,22.0
108634,ffee31fb4b5e35c9123608015637c495,1,b10ecf8e33aaaea419a9fa860ea80fb5,0241d4d5d36f10f80c644447315af0bd,2018-08-21 10:10:11,99.0,13.52,99.0,furniture_decor,11e0f43ab4e2d2c48348dd9332c0ef80,...,2018-08-18 10:00:59,2018-08-21 12:18:57,3,30.0,308.0,1.0,2300.0,37.0,30.0,20.0
108635,fff7c4452f050315db1b3f24d9df5fcd,1,dd469c03ad67e201bc2179ef077dcd48,7e93a43ef30c4f03f38b393420bc753a,2017-06-07 17:05:23,736.0,20.91,736.0,watches_gifts,dec8952e97ef6124259c56914fb3569c,...,2017-06-01 16:53:03,2017-06-08 13:04:40,7,33.0,658.0,3.0,400.0,19.0,9.0,15.0
108636,fffa82886406ccf10c7b4e35c4ff2788,1,bbe7651fef80287a816ead73f065fc4b,8f2ce03f928b567e3d56181ae20ae952,2017-12-22 17:31:42,229.9,44.02,229.9,sports_leisure,a5201e1a6d71a8d21e869151bd5b4085,...,2017-12-18 16:33:07,2018-01-08 18:23:10,21,32.0,280.0,2.0,2700.0,60.0,15.0,15.0
108637,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.0,12.79,43.0,bed_bath_table,96d649da0cc4ff33bb408b199d4c7dcf,...,2018-06-09 17:00:18,2018-06-14 17:56:26,5,47.0,511.0,1.0,600.0,30.0,3.0,19.0

In [ ]:
merge_order_category_size.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'accumulate_price',
       'product_category_name_english', 'customer_id', 'order_status',
       'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'order_purchase_date',
       'order_delivered_date', 'order_purchase_time', 'order_delivered_time',
       'total_date_of_delivery', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [ ]:
#check
merge_order_category_size[merge_order_category_size['order_purchase_date'].astype(str).str.contains('NaT')]

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value, accumulate_price, product_category_name_english, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, order_purchase_date, order_delivered_date, order_purchase_time, order_delivered_time, total_date_of_delivery, product_name_lenght, product_description_lenght, product_photos_qty, product_weight_g, product_length_cm, product_height_cm, product_width_cm]
Index: []

[0 rows x 28 columns]

In [ ]:
merge_order_category_size

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,accumulate_price,product_category_name_english,customer_id,...,order_purchase_time,order_delivered_time,total_date_of_delivery,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,58.9,cool_stuff,3ce436f183e68e07877b285a838db11a,...,2017-09-13 08:59:02,2017-09-20 23:43:48,7,58.0,598.0,4.0,650.0,28.0,9.0,14.0
1,130898c0987d1801452a8ed92a670612,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-07-05 02:44:11,55.9,17.96,55.9,cool_stuff,e6eecc5a77de221464d1c4eaff0a9b64,...,2017-06-28 11:52:20,2017-07-13 20:39:29,15,58.0,598.0,4.0,650.0,28.0,9.0,14.0
2,532ed5e14e24ae1f0d735b91524b98b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2018-05-23 10:56:25,64.9,18.33,64.9,cool_stuff,4ef55bf80f711b372afebcb7c715344a,...,2018-05-18 10:25:53,2018-06-04 18:34:26,17,58.0,598.0,4.0,650.0,28.0,9.0,14.0
3,6f8c31653edb8c83e1a739408b5ff750,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-07 18:55:08,58.9,16.17,58.9,cool_stuff,30407a72ad8b3f4df4d15369126b20c9,...,2017-08-01 18:38:42,2017-08-09 21:26:33,8,58.0,598.0,4.0,650.0,28.0,9.0,14.0
4,7d19f4ef4d04461989632411b7e588b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-16 22:05:11,58.9,13.29,58.9,cool_stuff,91a792fef70ecd8cc69d3c7feb3d12da,...,2017-08-10 21:48:40,2017-08-24 20:04:21,14,58.0,598.0,4.0,650.0,28.0,9.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108633,ffebd80e3291e811c308365936897efd,1,4cc4d02efc8f249c13355147fb44e34d,d1c7fa84e48cfa21a0e595167c1c500e,2018-07-18 20:23:55,129.9,51.20,129.9,garden_tools,050309b91cc5e04e68841938e7984aaf,...,2018-07-13 20:04:05,2018-07-23 19:44:45,10,37.0,653.0,1.0,6700.0,35.0,12.0,22.0
108634,ffee31fb4b5e35c9123608015637c495,1,b10ecf8e33aaaea419a9fa860ea80fb5,0241d4d5d36f10f80c644447315af0bd,2018-08-21 10:10:11,99.0,13.52,99.0,furniture_decor,11e0f43ab4e2d2c48348dd9332c0ef80,...,2018-08-18 10:00:59,2018-08-21 12:18:57,3,30.0,308.0,1.0,2300.0,37.0,30.0,20.0
108635,fff7c4452f050315db1b3f24d9df5fcd,1,dd469c03ad67e201bc2179ef077dcd48,7e93a43ef30c4f03f38b393420bc753a,2017-06-07 17:05:23,736.0,20.91,736.0,watches_gifts,dec8952e97ef6124259c56914fb3569c,...,2017-06-01 16:53:03,2017-06-08 13:04:40,7,33.0,658.0,3.0,400.0,19.0,9.0,15.0
108636,fffa82886406ccf10c7b4e35c4ff2788,1,bbe7651fef80287a816ead73f065fc4b,8f2ce03f928b567e3d56181ae20ae952,2017-12-22 17:31:42,229.9,44.02,229.9,sports_leisure,a5201e1a6d71a8d21e869151bd5b4085,...,2017-12-18 16:33:07,2018-01-08 18:23:10,21,32.0,280.0,2.0,2700.0,60.0,15.0,15.0
108637,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.0,12.79,43.0,bed_bath_table,96d649da0cc4ff33bb408b199d4c7dcf,...,2018-06-09 17:00:18,2018-06-14 17:56:26,5,47.0,511.0,1.0,600.0,30.0,3.0,19.0

# Add info into Master DF

In [ ]:
cust_order_df

,order_id,customer_id,customer_unique_id,customer_city,customer_state,state_fullname,order_freq_from_customer
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,São Paulo,2
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,af07308b275d755c9edb36a90c618231,barreiras,BA,Bahia,1
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO,Goiás,1
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN,Rio Grande do Norte,1
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP,São Paulo,1
...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,6359f309b166b0196dbf7ad2ac62bb5a,sao jose dos campos,SP,São Paulo,1
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,da62f9e57a76d978d02ab5362c509660,praia grande,SP,São Paulo,1
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,737520a9aad80b3fbbdad19b66b37b30,nova vicosa,BA,Bahia,1
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ,Rio de Janeiro,1
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,60350aa974b26ff12caad89e55993bd6,lapa,PR,Paraná,1

In [ ]:
# Add seller location + customer_id location / Average  income by state (income_mapping)(map())
#Average  income by state
import pandas as pd

mapping_income = {'SP':3462,'RJ':1449,'MG':1888,'RS':2404
,'PR':2389,'SC':2397,'BA':1546,'DF':3896,'ES':2061
,'GO':2038,'AC':1660,'AL':1343,'AM':1868,'AP':2212
,'CE':1503,'MA':598,'MG':1888,'MS':2129,'MT':2154
,'PA':1395,'PB':1593,'PE':1627,'PI':1290,'RJ':2336
,'RN':1512,'RO':1771,'RR':2074,'SE':1554,'TO':1724}


cust_oder_df_drop = cust_order_df.drop(columns=['customer_id'])
order_category_size_sate = pd.merge(merge_order_category_size,cust_oder_df_drop,on="order_id")
order_category_size_sate['average_income_by_state'] = order_category_size_sate['customer_state'].map(mapping_income)
order_category_size_sate

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,accumulate_price,product_category_name_english,customer_id,...,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,customer_city,customer_state,state_fullname,order_freq_from_customer,average_income_by_state
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,58.9,cool_stuff,3ce436f183e68e07877b285a838db11a,...,650.0,28.0,9.0,14.0,871766c5855e863f6eccc05f988b23cb,campos dos goytacazes,RJ,Rio de Janeiro,1,2336
1,130898c0987d1801452a8ed92a670612,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-07-05 02:44:11,55.9,17.96,55.9,cool_stuff,e6eecc5a77de221464d1c4eaff0a9b64,...,650.0,28.0,9.0,14.0,0fb8e3eab2d3e79d92bb3fffbb97f188,jatai,GO,Goiás,1,2038
2,532ed5e14e24ae1f0d735b91524b98b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2018-05-23 10:56:25,64.9,18.33,64.9,cool_stuff,4ef55bf80f711b372afebcb7c715344a,...,650.0,28.0,9.0,14.0,3419052c8c6b45daf79c1e426f9e9bcb,belo horizonte,MG,Minas Gerais,1,1888
3,6f8c31653edb8c83e1a739408b5ff750,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-07 18:55:08,58.9,16.17,58.9,cool_stuff,30407a72ad8b3f4df4d15369126b20c9,...,650.0,28.0,9.0,14.0,e7c828d22c0682c1565252deefbe334d,sao jose dos pinhais,PR,Paraná,1,2389
4,7d19f4ef4d04461989632411b7e588b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-16 22:05:11,58.9,13.29,58.9,cool_stuff,91a792fef70ecd8cc69d3c7feb3d12da,...,650.0,28.0,9.0,14.0,0bb98ba72dcc08e95f9d8cc434e9a2cc,conselheiro lafaiete,MG,Minas Gerais,1,1888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108633,ffebd80e3291e811c308365936897efd,1,4cc4d02efc8f249c13355147fb44e34d,d1c7fa84e48cfa21a0e595167c1c500e,2018-07-18 20:23:55,129.9,51.20,129.9,garden_tools,050309b91cc5e04e68841938e7984aaf,...,6700.0,35.0,12.0,22.0,a1c2e4b4c1b29e41684ebdf3cc6538f8,conceicao de macabu,RJ,Rio de Janeiro,1,2336
108634,ffee31fb4b5e35c9123608015637c495,1,b10ecf8e33aaaea419a9fa860ea80fb5,0241d4d5d36f10f80c644447315af0bd,2018-08-21 10:10:11,99.0,13.52,99.0,furniture_decor,11e0f43ab4e2d2c48348dd9332c0ef80,...,2300.0,37.0,30.0,20.0,4e15fee963523774998876e3624952f4,sao jose dos pinhais,PR,Paraná,2,2389
108635,fff7c4452f050315db1b3f24d9df5fcd,1,dd469c03ad67e201bc2179ef077dcd48,7e93a43ef30c4f03f38b393420bc753a,2017-06-07 17:05:23,736.0,20.91,736.0,watches_gifts,dec8952e97ef6124259c56914fb3569c,...,400.0,19.0,9.0,15.0,c86ab5ff2bac777c4e770a383feca4eb,volta redonda,RJ,Rio de Janeiro,1,2336
108636,fffa82886406ccf10c7b4e35c4ff2788,1,bbe7651fef80287a816ead73f065fc4b,8f2ce03f928b567e3d56181ae20ae952,2017-12-22 17:31:42,229.9,44.02,229.9,sports_leisure,a5201e1a6d71a8d21e869151bd5b4085,...,2700.0,60.0,15.0,15.0,2a3ab9bf9639491997586882c502540a,tenente ananias,RN,Rio Grande do Norte,1,1512
108637,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.0,12.79,43.0,bed_bath_table,96d649da0cc4ff33bb408b199d4c7dcf,...,600.0,30.0,3.0,19.0,cd76a00d8e3ca5e6ab9ed9ecb6667ac4,botucatu,SP,São Paulo,1,3462

In [ ]:
seller_data = pd.read_csv('/content/olist_sellers_dataset.csv')
seller_data

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [ ]:

#Seller
mapping = {"AC":'Acre',"AL":'Alagoas',"AM":'Amazonas',
'AP':'Amapá','BA':'Bahia','CE':'Ceará',
'DF':'Distrito Federal','ES':'Espírito Santo','GO':'Goiás',
'MA':'Maranhão',
'MG':'Minas Gerais',
'MS':'Mato Grosso do Sul',
'MT':'Mato Grosso',
'PA':'Pará',
'PB':'Paraíba',
'PE':'Pernambuco',
'PI':'Piauí',
'PR':'Paraná',
'RJ':'Rio de Janeiro',
'RN':'Rio Grande do Norte',
'RO':'Rondônia',
'RR':'Roraima',
'RS':'Rio Grande do Sul',
'SC':'Santa Catarina',
'SE':'Sergipe',
'SP':'São Paulo',
'TO':'Tocantins'}

seller_data_drop = seller_data.drop(columns="seller_zip_code_prefix")
master_df = pd.merge(order_category_size_sate, seller_data_drop,on='seller_id')
master_df['state_fullname_seller'] = master_df['seller_state'].map(mapping)
#master_df[master_df['seller_state'] == "TO"]

In [ ]:
#check
master_df[master_df['order_delivered_date'].isnull()]

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value, accumulate_price, product_category_name_english, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, order_purchase_date, order_delivered_date, order_purchase_time, order_delivered_time, total_date_of_delivery, product_name_lenght, product_description_lenght, product_photos_qty, product_weight_g, product_length_cm, product_height_cm, product_width_cm, customer_unique_id, customer_city, customer_state, state_fullname, order_freq_from_customer, average_income_by_state, seller_city, seller_state, state_fullname_seller]
Index: []

[0 rows x 37 columns]

In [ ]:
master_df

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,accumulate_price,product_category_name_english,customer_id,...,product_width_cm,customer_unique_id,customer_city,customer_state,state_fullname,order_freq_from_customer,average_income_by_state,seller_city,seller_state,state_fullname_seller
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29,58.9,cool_stuff,3ce436f183e68e07877b285a838db11a,...,14.0,871766c5855e863f6eccc05f988b23cb,campos dos goytacazes,RJ,Rio de Janeiro,1,2336,volta redonda,SP,São Paulo
1,130898c0987d1801452a8ed92a670612,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-07-05 02:44:11,55.9,17.96,55.9,cool_stuff,e6eecc5a77de221464d1c4eaff0a9b64,...,14.0,0fb8e3eab2d3e79d92bb3fffbb97f188,jatai,GO,Goiás,1,2038,volta redonda,SP,São Paulo
2,532ed5e14e24ae1f0d735b91524b98b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2018-05-23 10:56:25,64.9,18.33,64.9,cool_stuff,4ef55bf80f711b372afebcb7c715344a,...,14.0,3419052c8c6b45daf79c1e426f9e9bcb,belo horizonte,MG,Minas Gerais,1,1888,volta redonda,SP,São Paulo
3,6f8c31653edb8c83e1a739408b5ff750,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-07 18:55:08,58.9,16.17,58.9,cool_stuff,30407a72ad8b3f4df4d15369126b20c9,...,14.0,e7c828d22c0682c1565252deefbe334d,sao jose dos pinhais,PR,Paraná,1,2389,volta redonda,SP,São Paulo
4,7d19f4ef4d04461989632411b7e588b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-16 22:05:11,58.9,13.29,58.9,cool_stuff,91a792fef70ecd8cc69d3c7feb3d12da,...,14.0,0bb98ba72dcc08e95f9d8cc434e9a2cc,conselheiro lafaiete,MG,Minas Gerais,1,1888,volta redonda,SP,São Paulo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108633,fdaf98feac227eb978d8f33f36e0231d,1,f739e9151702508b18f796c53005e5e9,d1aa1ec0839dcab73a6161130eb1f94a,2017-04-27 05:10:28,119.9,16.14,119.9,furniture_decor,81ae83ce1a10af9f93fa3512bd9713b1,...,11.0,3d50a44231c2a153219cef76ee3e445d,rio de janeiro,RJ,Rio de Janeiro,2,2336,curitiba,PR,Paraná
108634,fe68b52db13993f58175fa589125d345,1,f4135cbdece8245560f7be179533797a,3fefda3299e6dfaea3466ef346a3571a,2017-08-17 02:55:27,209.0,16.21,209.0,electronics,94203a446c1b46b5ac95b0aaf7221804,...,25.0,52a953541861bbb4b79b39df24e00243,limeira,SP,São Paulo,1,3462,curitiba,PR,Paraná
108635,fefacc66af859508bf1a7934eab1e97f,1,69c590f7ffc7bf8db97190b6cb6ed62e,80ceebb4ee9b31afb6c6a916a574a1e2,2018-08-02 04:05:13,6729.0,193.21,6729.0,computers,f48d464a0baaea338cb25f816991ab1f,...,47.0,459bef486812aa25204be022145caa62,vitoria,ES,Espírito Santo,1,2061,londrina,PR,Paraná
108636,ff701a7c869ad21de22a6994237c8a00,1,5ff4076c0f01eeba4f728c9e3fa2653c,3e35a8bb43569389d3cebef0ce820f69,2018-04-18 20:10:33,27.9,14.44,55.8,drinks,8f6d16c31abb30b7b4650272cb0014a3,...,19.0,ddb2249e0316d365ceae561c0f011bce,cacapava,SP,São Paulo,1,3462,sao paulo,SP,São Paulo
108637,ff701a7c869ad21de22a6994237c8a00,2,5ff4076c0f01eeba4f728c9e3fa2653c,3e35a8bb43569389d3cebef0ce820f69,2018-04-18 20:10:33,27.9,14.44,55.8,drinks,8f6d16c31abb30b7b4650272cb0014a3,...,19.0,ddb2249e0316d365ceae561c0f011bce,cacapava,SP,São Paulo,1,3462,sao paulo,SP,São Paulo

# Add a timeline in power bi

In [ ]:
master_df.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'accumulate_price',
       'product_category_name_english', 'customer_id', 'order_status',
       'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'order_purchase_date',
       'order_delivered_date', 'order_purchase_time', 'order_delivered_time',
       'total_date_of_delivery', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'customer_unique_id', 'customer_city', 'customer_state',
       'state_fullname', 'order_freq_from_customer', 'average_income_by_state',
       'seller_city', 'seller_state', 'state_fullname_seller'],
      dtype='object')

In [ ]:
master_df[['order_purchase_date','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_delivered_date','order_estimated_delivery_date']]

,order_purchase_date,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_delivered_date,order_estimated_delivery_date
0,2017-09-13,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-20,2017-09-29 00:00:00
1,2017-06-28,2017-06-29 02:44:11,2017-07-05 12:00:33,2017-07-13 20:39:29,2017-07-13,2017-07-26 00:00:00
2,2018-05-18,2018-05-18 12:31:43,2018-05-23 14:05:00,2018-06-04 18:34:26,2018-06-04,2018-06-07 00:00:00
3,2017-08-01,2017-08-01 18:55:08,2017-08-02 19:07:36,2017-08-09 21:26:33,2017-08-09,2017-08-25 00:00:00
4,2017-08-10,2017-08-10 22:05:11,2017-08-11 19:43:07,2017-08-24 20:04:21,2017-08-24,2017-09-01 00:00:00
...,...,...,...,...,...,...
108633,2017-04-19,2017-04-21 05:10:28,2017-05-04 15:06:24,2017-05-24 10:52:43,2017-05-24,2017-05-22 00:00:00
108634,2017-08-11,2017-08-12 02:55:27,2017-08-14 22:03:19,2017-08-17 17:47:55,2017-08-17,2017-09-04 00:00:00
108635,2018-07-25,2018-07-27 04:05:13,2018-08-03 14:42:00,2018-08-15 14:57:50,2018-08-15,2018-08-10 00:00:00
108636,2018-04-12,2018-04-12 20:10:33,2018-04-18 00:41:29,2018-04-20 17:48:39,2018-04-20,2018-04-30 00:00:00
108637,2018-04-12,2018-04-12 20:10:33,2018-04-18 00:41:29,2018-04-20 17:48:39,2018-04-20,2018-04-30 00:00:00

In [ ]:
master_df['order_delivered_carrier_date'].info()

<class 'pandas.core.series.Series'>
Int64Index: 108638 entries, 0 to 108637
Series name: order_delivered_carrier_date
Non-Null Count   Dtype
--------------   -----
108638 non-null  object
dtypes: object(1)
memory usage: 1.7+ MB

In [ ]:
#Change to datetime first
master_df['order_approved_at'] = pd.to_datetime(master_df['order_approved_at'])
master_df['order_delivered_carrier_date'] = pd.to_datetime(master_df['order_delivered_carrier_date'])

#then add columns with date only
master_df['order_approved_at_date'] = pd.to_datetime(master_df['order_approved_at'].dt.strftime('%Y-%m-%d'))
master_df['order_delivered_carrier_date_'] = pd.to_datetime(master_df['order_delivered_carrier_date'].dt.strftime('%Y-%m-%d'))

timeline_df = master_df[['order_id','product_category_name_english','state_fullname','state_fullname_seller','total_date_of_delivery','order_purchase_date','order_approved_at_date','order_delivered_carrier_date_','order_delivered_date']]
timeline_df

,order_id,product_category_name_english,state_fullname,state_fullname_seller,total_date_of_delivery,order_purchase_date,order_approved_at_date,order_delivered_carrier_date_,order_delivered_date
0,00010242fe8c5a6d1ba2dd792cb16214,cool_stuff,Rio de Janeiro,São Paulo,7,2017-09-13,2017-09-13,2017-09-19,2017-09-20
1,130898c0987d1801452a8ed92a670612,cool_stuff,Goiás,São Paulo,15,2017-06-28,2017-06-29,2017-07-05,2017-07-13
2,532ed5e14e24ae1f0d735b91524b98b9,cool_stuff,Minas Gerais,São Paulo,17,2018-05-18,2018-05-18,2018-05-23,2018-06-04
3,6f8c31653edb8c83e1a739408b5ff750,cool_stuff,Paraná,São Paulo,8,2017-08-01,2017-08-01,2017-08-02,2017-08-09
4,7d19f4ef4d04461989632411b7e588b9,cool_stuff,Minas Gerais,São Paulo,14,2017-08-10,2017-08-10,2017-08-11,2017-08-24
...,...,...,...,...,...,...,...,...,...
108633,fdaf98feac227eb978d8f33f36e0231d,furniture_decor,Rio de Janeiro,Paraná,35,2017-04-19,2017-04-21,2017-05-04,2017-05-24
108634,fe68b52db13993f58175fa589125d345,electronics,São Paulo,Paraná,6,2017-08-11,2017-08-12,2017-08-14,2017-08-17
108635,fefacc66af859508bf1a7934eab1e97f,computers,Espírito Santo,Paraná,21,2018-07-25,2018-07-27,2018-08-03,2018-08-15
108636,ff701a7c869ad21de22a6994237c8a00,drinks,São Paulo,São Paulo,8,2018-04-12,2018-04-12,2018-04-18,2018-04-20
108637,ff701a7c869ad21de22a6994237c8a00,drinks,São Paulo,São Paulo,8,2018-04-12,2018-04-12,2018-04-18,2018-04-20

# Accurate calculation for timelines (drop_duplicates)

In [ ]:
master_df_new = master_df.drop_duplicates(subset="order_id")
master_df_new

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,accumulate_price,product_category_name_english,customer_id,...,customer_city,customer_state,state_fullname,order_freq_from_customer,average_income_by_state,seller_city,seller_state,state_fullname_seller,order_approved_at_date,order_delivered_carrier_date_
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,58.90,cool_stuff,3ce436f183e68e07877b285a838db11a,...,campos dos goytacazes,RJ,Rio de Janeiro,1,2336,volta redonda,SP,São Paulo,2017-09-13,2017-09-19
1,130898c0987d1801452a8ed92a670612,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-07-05 02:44:11,55.90,17.96,55.90,cool_stuff,e6eecc5a77de221464d1c4eaff0a9b64,...,jatai,GO,Goiás,1,2038,volta redonda,SP,São Paulo,2017-06-29,2017-07-05
2,532ed5e14e24ae1f0d735b91524b98b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2018-05-23 10:56:25,64.90,18.33,64.90,cool_stuff,4ef55bf80f711b372afebcb7c715344a,...,belo horizonte,MG,Minas Gerais,1,1888,volta redonda,SP,São Paulo,2018-05-18,2018-05-23
3,6f8c31653edb8c83e1a739408b5ff750,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-07 18:55:08,58.90,16.17,58.90,cool_stuff,30407a72ad8b3f4df4d15369126b20c9,...,sao jose dos pinhais,PR,Paraná,1,2389,volta redonda,SP,São Paulo,2017-08-01,2017-08-02
4,7d19f4ef4d04461989632411b7e588b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-16 22:05:11,58.90,13.29,58.90,cool_stuff,91a792fef70ecd8cc69d3c7feb3d12da,...,conselheiro lafaiete,MG,Minas Gerais,1,1888,volta redonda,SP,São Paulo,2017-08-10,2017-08-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108631,fd607d0a02cb276bc764a15f80f0423f,1,02ad78835ec3f72e750d1dfa6a7e11b3,2a73cba571d90c694b7caca072ccf6ce,2018-08-02 02:24:15,171.39,19.35,342.78,furniture_decor,fef79774a4f4ef014078bcb0b42d0cc5,...,salvador,BA,Bahia,1,1546,sao caetano do sul,SP,São Paulo,2018-07-27,2018-08-07
108633,fdaf98feac227eb978d8f33f36e0231d,1,f739e9151702508b18f796c53005e5e9,d1aa1ec0839dcab73a6161130eb1f94a,2017-04-27 05:10:28,119.90,16.14,119.90,furniture_decor,81ae83ce1a10af9f93fa3512bd9713b1,...,rio de janeiro,RJ,Rio de Janeiro,2,2336,curitiba,PR,Paraná,2017-04-21,2017-05-04
108634,fe68b52db13993f58175fa589125d345,1,f4135cbdece8245560f7be179533797a,3fefda3299e6dfaea3466ef346a3571a,2017-08-17 02:55:27,209.00,16.21,209.00,electronics,94203a446c1b46b5ac95b0aaf7221804,...,limeira,SP,São Paulo,1,3462,curitiba,PR,Paraná,2017-08-12,2017-08-14
108635,fefacc66af859508bf1a7934eab1e97f,1,69c590f7ffc7bf8db97190b6cb6ed62e,80ceebb4ee9b31afb6c6a916a574a1e2,2018-08-02 04:05:13,6729.00,193.21,6729.00,computers,f48d464a0baaea338cb25f816991ab1f,...,vitoria,ES,Espírito Santo,1,2061,londrina,PR,Paraná,2018-07-27,2018-08-03
108636,ff701a7c869ad21de22a6994237c8a00,1,5ff4076c0f01eeba4f728c9e3fa2653c,3e35a8bb43569389d3cebef0ce820f69,2018-04-18 20:10:33,27.90,14.44,55.80,drinks,8f6d16c31abb30b7b4650272cb0014a3,...,cacapava,SP,São Paulo,1,3462,sao paulo,SP,São Paulo,2018-04-12,2018-04-18

In [ ]:
# purchase to approve days
master_df_new['pur_appro_days'] = master_df_new['order_approved_at_date'] - master_df_new['order_purchase_date']

mapping_pur_appro_days = master_df_new['pur_appro_days'].astype(str).str.replace(' days','').to_dict()
master_df_new['pur_appro_days'] = master_df_new.index.map(mapping_pur_appro_days)
master_df_new['pur_appro_days'] = master_df_new['pur_appro_days'].astype(int)
master_df_new['pur_appro_days']

<ipython-input-170-3ebe66857f28>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df_new['pur_appro_days'] = master_df_new['order_approved_at_date'] - master_df_new['order_purchase_date']
<ipython-input-170-3ebe66857f28>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df_new['pur_appro_days'] = master_df_new.index.map(mapping_pur_appro_days)
<ipython-input-170-3ebe66857f28>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df_new['pur_appro_days'] = master_df_new['pur_appro_days'].astype(int)

0         0
1         1
2         0
3         0
4         0
         ..
108631    1
108633    2
108634    1
108635    2
108636    0
Name: pur_appro_days, Length: 95127, dtype: int64

In [ ]:
# approve to carrier
master_df_new['appro_carrier_days'] = master_df_new['order_delivered_carrier_date_'] - master_df_new['order_approved_at_date']

mapping_appro_carrier_days = master_df_new['appro_carrier_days'].astype(str).str.replace(' days','').to_dict()
master_df_new['appro_carrier_days'] = master_df_new.index.map(mapping_appro_carrier_days)
master_df_new['appro_carrier_days'] = master_df_new['appro_carrier_days'].astype(int)
master_df_new['appro_carrier_days']

<ipython-input-176-842e6193a359>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df_new['appro_carrier_days'] = master_df_new['order_delivered_carrier_date_'] - master_df_new['order_approved_at_date']
<ipython-input-176-842e6193a359>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df_new['appro_carrier_days'] = master_df_new.index.map(mapping_appro_carrier_days)
<ipython-input-176-842e6193a359>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df_new['appro_carrier_days'] = master_df_new['appro_carrier_days'].astype(int)

0          6
1          6
2          5
3          1
4          1
          ..
108631    11
108633    13
108634     2
108635     7
108636     6
Name: appro_carrier_days, Length: 95127, dtype: int64

In [ ]:
# carrier to delivered
master_df_new['carrier_delivered_days'] = master_df_new['order_delivered_date'] - master_df_new['order_delivered_carrier_date_']

mapping_carrier_delivered_days = master_df_new['carrier_delivered_days'].astype(str).str.replace(' days','').to_dict()
master_df_new['carrier_delivered_days'] = master_df_new.index.map(mapping_carrier_delivered_days)
master_df_new['carrier_delivered_days'] = master_df_new['carrier_delivered_days'].astype(int)
master_df_new['carrier_delivered_days']

<ipython-input-175-bf850418c90a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df_new['carrier_delivered_days'] = master_df_new['order_delivered_date'] - master_df_new['order_delivered_carrier_date_']
<ipython-input-175-bf850418c90a>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df_new['carrier_delivered_days'] = master_df_new.index.map(mapping_carrier_delivered_days)
<ipython-input-175-bf850418c90a>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df_new['carrier_delivered_days'] = master_df_new['carrier_delivered_days'].astype(int)

0          1
1          8
2         12
3          7
4         13
          ..
108631     9
108633    20
108634     3
108635    12
108636     2
Name: carrier_delivered_days, Length: 95127, dtype: int64

In [ ]:
#Check shipping limited time (seller pass order to carrier)
master_df_new['shipping_limit_date'] = pd.to_datetime(master_df_new['shipping_limit_date'])

master_df_new['seller_to_carrier_date'] = pd.to_datetime(master_df_new['shipping_limit_date'].dt.strftime('%Y-%m-%d'))
master_df_new['seller_to_carrier_date']

<ipython-input-178-ce27ee0a97eb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df_new['shipping_limit_date'] = pd.to_datetime(master_df_new['shipping_limit_date'])
<ipython-input-178-ce27ee0a97eb>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df_new['seller_to_carrier_date'] = pd.to_datetime(master_df_new['shipping_limit_date'].dt.strftime('%Y-%m-%d'))

0        2017-09-19
1        2017-07-05
2        2018-05-23
3        2017-08-07
4        2017-08-16
            ...
108631   2018-08-02
108633   2017-04-27
108634   2017-08-17
108635   2018-08-02
108636   2018-04-18
Name: seller_to_carrier_date, Length: 95127, dtype: datetime64[ns]

In [ ]:
master_df_new['seller_to_carrier_intervals'] = master_df_new['seller_to_carrier_date'] - master_df_new['order_delivered_carrier_date_']
mapping_seller_to_carrier = master_df_new['seller_to_carrier_intervals'].astype(str).str.replace(' days','').to_dict()
master_df_new['seller_to_carrier_intervals'] = master_df_new.index.map(mapping_seller_to_carrier)

#Change to int
master_df_new['seller_to_carrier_intervals'] = master_df_new['seller_to_carrier_intervals'].astype(int)
master_df_new['seller_to_carrier_intervals'].describe()

<ipython-input-186-138a66fc6449>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df_new['seller_to_carrier_intervals'] = master_df_new['seller_to_carrier_date'] - master_df_new['order_delivered_carrier_date_']
<ipython-input-186-138a66fc6449>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df_new['seller_to_carrier_intervals'] = master_df_new.index.map(mapping_seller_to_carrier)
<ipython-input-186-138a66fc6449>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  master_df_new['seller_to_carrier_intervals'] = master_df_new['seller_to_carrier_intervals'].astype(int)

count    95127.000000
mean         3.444553
std          5.060695
min        -95.000000
25%          2.000000
50%          3.000000
75%          5.000000
max       1046.000000
Name: seller_to_carrier_intervals, dtype: float64

In [ ]:
master_df_new.to_csv('/content/drive/MyDrive/Colab Notebooks/olist_master_df_v3_for_timeline.csv')

# Price range 0-50,50-70...... refix the range from finalproject-colab(version1)

In [ ]:
master_df['accumulate_price']

0           58.9
1           55.9
2           64.9
3           58.9
4           58.9
           ...
108633     119.9
108634     209.0
108635    6729.0
108636      55.8
108637      55.8
Name: accumulate_price, Length: 108638, dtype: float64

In [ ]:
between_0_50 = master_df[(master_df['accumulate_price'] >=0) & (master_df['accumulate_price'] <=50)]
between_0_50_drop = between_0_50.drop_duplicates(subset='order_id')
between_0_50_drop

In [ ]:
#find orders that sales in between 50-70 (13888 orders)
between_50_70 = master_df[(master_df['accumulate_price'] >50) & (master_df['accumulate_price'] <=70)]
# clean data with no repeat orders (12804 orders)
between_50_70_drop = between_50_70.drop_duplicates(subset='order_id')
between_50_70_drop

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,accumulate_price,product_category_name_english,customer_id,...,product_width_cm,customer_unique_id,customer_city,customer_state,state_fullname,order_freq_from_customer,average_income_by_state,seller_city,seller_state,state_fullname_seller
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,58.90,cool_stuff,3ce436f183e68e07877b285a838db11a,...,14.0,871766c5855e863f6eccc05f988b23cb,campos dos goytacazes,RJ,Rio de Janeiro,1,2336,volta redonda,SP,São Paulo
1,130898c0987d1801452a8ed92a670612,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-07-05 02:44:11,55.90,17.96,55.90,cool_stuff,e6eecc5a77de221464d1c4eaff0a9b64,...,14.0,0fb8e3eab2d3e79d92bb3fffbb97f188,jatai,GO,Goiás,1,2038,volta redonda,SP,São Paulo
2,532ed5e14e24ae1f0d735b91524b98b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2018-05-23 10:56:25,64.90,18.33,64.90,cool_stuff,4ef55bf80f711b372afebcb7c715344a,...,14.0,3419052c8c6b45daf79c1e426f9e9bcb,belo horizonte,MG,Minas Gerais,1,1888,volta redonda,SP,São Paulo
3,6f8c31653edb8c83e1a739408b5ff750,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-07 18:55:08,58.90,16.17,58.90,cool_stuff,30407a72ad8b3f4df4d15369126b20c9,...,14.0,e7c828d22c0682c1565252deefbe334d,sao jose dos pinhais,PR,Paraná,1,2389,volta redonda,SP,São Paulo
4,7d19f4ef4d04461989632411b7e588b9,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-16 22:05:11,58.90,13.29,58.90,cool_stuff,91a792fef70ecd8cc69d3c7feb3d12da,...,14.0,0bb98ba72dcc08e95f9d8cc434e9a2cc,conselheiro lafaiete,MG,Minas Gerais,1,1888,volta redonda,SP,São Paulo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108559,dd9768256f9f491643fb7b53fc193b7d,1,3de040f7129e3e1aa3a1fd1d6c1f9f2d,d85efbc8eff2b7adf524e2820569adc8,2018-05-20 23:16:32,55.00,8.29,55.00,stationery,96bc42e21c7f606d1920c12965f67109,...,25.0,a6ee14e78faef91d8abda3bde561219f,atibaia,SP,São Paulo,1,3462,sao paulo,SP,São Paulo
108577,e3956b68479689ff22eaf1f931ddaa29,1,6647429facfcec3f6bb7162c85985c6b,0b1ca3ef18a63d7eb0c8897fa0849c08,2018-04-19 02:11:31,55.00,7.87,55.00,health_beauty,79cfcbd00dfce1c4e9208032ab7aab15,...,11.0,acaf5177d6de60fda7ce77c48abb5230,suzano,SP,São Paulo,3,3462,sao roque,SP,São Paulo
108585,e8e55eaa809f3091cc5060cc53735660,1,7edd6cf84eed8d7a3b63543734fb1249,447d377bdb757058acb569025ee18a93,2018-02-08 19:31:18,64.99,18.02,64.99,stationery,2ca5f0111cef8030082e8adf6a068f6d,...,35.0,f86871c7161e1c8cec811766e1594628,itaperuna,RJ,Rio de Janeiro,1,2336,carazinho,RS,Rio Grande do Sul
108609,f1c81a653dc5314b7aa62e06239f12c8,1,7368c0d612a177b6cb085f56b823dc08,edb65fe661681b1c0de8bd47c8655855,2017-05-04 12:34:35,69.00,15.24,69.00,small_appliances,0dfe60b670deaf534a0d9519349169d0,...,11.0,1b105048a36cf31dbbac4a2eda6ed1fa,belo horizonte,MG,Minas Gerais,1,1888,sao paulo,SP,São Paulo
108636,ff701a7c869ad21de22a6994237c8a00,1,5ff4076c0f01eeba4f728c9e3fa2653c,3e35a8bb43569389d3cebef0ce820f69,2018-04-18 20:10:33,27.90,14.44,55.80,drinks,8f6d16c31abb30b7b4650272cb0014a3,...,19.0,ddb2249e0316d365ceae561c0f011bce,cacapava,SP,São Paulo,1,3462,sao paulo,SP,São Paulo

In [ ]:
between_50_70_drop.to_csv('/content/drive/MyDrive/Colab Notebooks/between_50_70_order.csv')

In [ ]:
# 70-79
#find orders that sales in between 70-79 ( 3683 orders)
between_70_79 = master_df[(master_df['accumulate_price'] >70) & (master_df['accumulate_price'] <=79)]
# clean data with no repeat orders ( 3220 orders)
between_70_79_drop = between_70_79.drop_duplicates(subset='order_id')
#between_70_79_drop

In [ ]:
between_70_79_drop.to_csv('/content/drive/MyDrive/Colab Notebooks/between_70_79_order.csv')

# check deliverty overtime

In [ ]:
masterdf_2 = master_df.copy()

In [ ]:
masterdf_2['order_estimated_delivery_date']

0         2017-09-29 00:00:00
1         2017-07-26 00:00:00
2         2018-06-07 00:00:00
3         2017-08-25 00:00:00
4         2017-09-01 00:00:00
                 ...
108633    2017-05-22 00:00:00
108634    2017-09-04 00:00:00
108635    2018-08-10 00:00:00
108636    2018-04-30 00:00:00
108637    2018-04-30 00:00:00
Name: order_estimated_delivery_date, Length: 108638, dtype: object

In [ ]:
masterdf_2['order_estimated_delivery_date'] = pd.to_datetime(masterdf_2['order_estimated_delivery_date'])
masterdf_2['order_estimated_delivery_date'] = pd.to_datetime(masterdf_2['order_estimated_delivery_date'].dt.strftime('%Y-%m-%d'))

In [ ]:
masterdf_2['check_overtime_delivery'] = masterdf_2['order_estimated_delivery_date'] - masterdf_2['order_delivered_date']
dict_overtime = masterdf_2['check_overtime_delivery'].astype(str).str.replace(' days','').to_dict()
masterdf_2['check_overtime_delivery'] = masterdf_2.index.map(dict_overtime)

masterdf_2['check_overtime_delivery'] = masterdf_2['check_overtime_delivery'].astype(int)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,...,average_income_by_state,seller_city,seller_state,state_fullname_seller,check_overtime_delivery
5,a0f9acf0b6294ed8561e32cde1a966bc,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-08-03 15:23:46,...,1546,volta redonda,SP,São Paulo,-7
62,34a9dd848ef0ebd4ae4b60d31720497d,1,c03d44fcdfabbabd5185c8eb60f77aea,48436dade18ac8b2bce089ec2a041202,2017-10-19 13:13:47,...,3462,volta redonda,SP,São Paulo,-11
88,acd7029e70d5e80091c71c9be6643758,1,c43ab4269cbf91b373263db4c2973cad,48436dade18ac8b2bce089ec2a041202,2017-08-08 03:04:48,...,2336,volta redonda,SP,São Paulo,-28
95,4a580bca631a940ffc9e25c96da01773,1,c9ea06f7fd4bd778e96031f46f60dfb9,48436dade18ac8b2bce089ec2a041202,2017-08-07 20:10:17,...,3462,volta redonda,SP,São Paulo,-78
101,2929e8208718655c26082e7331ef49e4,1,54e5939fcd9ae70ad0f59f612d6d29bd,48436dade18ac8b2bce089ec2a041202,2017-10-03 12:49:41,...,1395,volta redonda,SP,São Paulo,-4
...,...,...,...,...,...,...,...,...,...,...,...
108593,ecfc862cb2fabd3d5f9c86117a9baff0,1,5be29135cf368b56e0b1920b2e77989f,20f0aeea30bc3b8c4420be8ced4226c0,2017-02-11 19:13:56,...,2389,santa barbara d'oeste,SP,São Paulo,-13
108602,eeefa455d74943dff6a84508fcab8542,1,f2f80444318155ff4846edcb98aa8697,781a66c0d89e30814d49fe8b5e14cd07,2017-11-21 12:50:31,...,2397,campinas,SP,São Paulo,-10
108608,f1b3809a1da6d290236e12617e8be778,1,cd23ec4a774a11839255737299a05f4d,9bf11dfc0bec77e5a23028043c3c5a8f,2017-11-30 00:58:32,...,3462,contagem,MG,Minas Gerais,-12
108633,fdaf98feac227eb978d8f33f36e0231d,1,f739e9151702508b18f796c53005e5e9,d1aa1ec0839dcab73a6161130eb1f94a,2017-04-27 05:10:28,...,2336,curitiba,PR,Paraná,-2
108635,fefacc66af859508bf1a7934eab1e97f,1,69c590f7ffc7bf8db97190b6cb6ed62e,80ceebb4ee9b31afb6c6a916a574a1e2,2018-08-02 04:05:13,...,2061,londrina,PR,Paraná,-5

In [ ]:
delay = masterdf_2[masterdf_2['check_overtime_delivery'] <0]

In [ ]:
delay.describe()

,order_item_id,price,freight_value,accumulate_price,total_date_of_delivery,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,order_freq_from_customer,average_income_by_state,check_overtime_delivery
count,7148.000000,7148.000000,7148.000000,7148.000000,7148.000000,7148.000000,7148.000000,7148.000000,7148.000000,7148.000000,7148.000000,7148.000000,7148.000000,7148.000000,7148.000000
mean,1.173055,135.950042,22.761801,159.257245,33.749860,48.951455,788.138220,2.184387,2471.922076,31.433968,17.335618,23.412563,1.064494,2456.438304,-10.482093
std,0.817033,214.356179,18.531220,235.624093,17.380968,9.837181,659.206236,1.768978,4427.970327,17.552926,14.506180,12.325289,0.303717,769.724316,14.447556
min,1.000000,1.200000,0.000000,3.540000,4.000000,9.000000,30.000000,1.000000,50.000000,11.000000,2.000000,8.000000,1.000000,598.000000,-188.000000
25%,1.000000,45.000000,15.065000,50.000000,24.000000,43.000000,341.000000,1.000000,300.000000,18.000000,9.000000,15.000000,1.000000,1888.000000,-13.000000
50%,1.000000,80.990000,17.670000,98.980000,31.000000,52.000000,602.000000,1.000000,800.000000,25.000000,13.000000,20.000000,1.000000,2336.000000,-7.000000
75%,1.000000,149.900000,23.422500,169.990000,40.000000,57.000000,991.500000,3.000000,2137.000000,40.000000,20.000000,30.000000,1.000000,3462.000000,-3.000000
max,21.000000,6729.000000,237.110000,6729.000000,210.000000,72.000000,3939.000000,19.000000,40425.000000,105.000000,105.000000,118.000000,9.000000,3896.000000,-1.000000

In [ ]:
#reference
mapping_seller_to_carrier = master_df_new['seller_to_carrier_intervals'].astype(str).str.replace(' days','').to_dict()
master_df_new['seller_to_carrier_intervals'] = master_df_new.index.map(mapping_seller_to_carrier)

#Change to int
master_df_new['seller_to_carrier_intervals'] = master_df_new['seller_to_carrier_intervals'].astype(int)
master_df_new['seller_to_carrier_intervals'].describe()